eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081
  servlet:
    context-path: /reservation

spring:
  application:
    name: nss-reservation-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${DB_NAME:nss}
    username: ${DB_USER:nss}
    password: ${DB_PASSWORD:nss}
  jpa:
    database-platform: org.eclipse.persistence.platform.database.PostgreSQLPlatform
    generate-ddl: true
    show-sql: false

logging:
  file:
    name: "application.log"